//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagesupply.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class registertbl
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string photo { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
